/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Cargo;
import dominio.ControlJuntaDirectiva;
import dominio.ControlSocio;
import dominio.Socio;
import java.util.ArrayList;

/**
 *
 * @author angel
 */
public class JuntaDirectiva extends javax.swing.JFrame {

    /**
     * Creates new form JuntaDirectiva
     */
    public JuntaDirectiva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TicketManagementSystem");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Guardar");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(180, 35));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.GridLayout(6, 2, 5, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Presidente:");
        jPanel3.add(jLabel1);

        rellenarComboBox();
        seleccionarCargo();
        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setBorder(null);
        jPanel3.add(jComboBox1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Vicepresidente:");
        jPanel3.add(jLabel2);

        jComboBox2.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox2.setBorder(null);
        jPanel3.add(jComboBox2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Secretario:");
        jPanel3.add(jLabel3);

        jComboBox3.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox3.setBorder(null);
        jPanel3.add(jComboBox3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Tesorero:");
        jPanel3.add(jLabel4);

        jComboBox4.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox4.setBorder(null);
        jPanel3.add(jComboBox4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Vocal1:");
        jPanel3.add(jLabel5);

        jComboBox5.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox5.setBorder(null);
        jPanel3.add(jComboBox5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Vocal2:");
        jPanel3.add(jLabel6);

        jComboBox6.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox6.setBorder(null);
        jPanel3.add(jComboBox6);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ControlJuntaDirectiva cjd = new ControlJuntaDirectiva();
        Cargo cargo = null;
        if(!jComboBox1.getSelectedItem().toString().equals("Ninguno")){
            String [] pres1 = jComboBox1.getSelectedItem().toString().split(" ");
            cargo = new Cargo("Presidente", pres1[0]);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }else{
            cargo = new Cargo("Presidente", null);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }
        
        if(!jComboBox2.getSelectedItem().toString().equals("Ninguno")){
            String [] pres2 = jComboBox2.getSelectedItem().toString().split(" ");
            cargo = new Cargo("Vicepresidente", pres2[0]);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }else{
            cargo = new Cargo("Vicepresidente", null);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }
        
        if(!jComboBox3.getSelectedItem().toString().equals("Ninguno")){
            String [] pres3 = jComboBox3.getSelectedItem().toString().split(" ");
            cargo = new Cargo("Secretario", pres3[0]);            
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }else{
            cargo = new Cargo("Secretario", null);            
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }
        
        if(!jComboBox4.getSelectedItem().toString().equals("Ninguno")){
            String [] pres4 = jComboBox4.getSelectedItem().toString().split(" ");
            cargo = new Cargo("Tesorero", pres4[0]);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }else{
            cargo = new Cargo("Tesorero",null);            
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }
        
        if(!jComboBox5.getSelectedItem().toString().equals("Ninguno")){
            String [] pres5 = jComboBox5.getSelectedItem().toString().split(" ");
            cargo = new Cargo("Vocal1",pres5[0]);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }else{
            cargo = new Cargo("Vocal1",null);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }
        
        if(!jComboBox6.getSelectedItem().toString().equals("Ninguno")){
            String [] pres6 = jComboBox6.getSelectedItem().toString().split(" ");
            cargo = new Cargo("Vocal2",pres6[0]);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }else{
            cargo = new Cargo("Vocal2",null);
            if(cjd.modificarCargo(cargo)){
                dispose();
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    //Selecciona el socio correspondiente en cada cargo
    private void seleccionarCargo(){
        Socio socio = null;
        ControlJuntaDirectiva cjd = new ControlJuntaDirectiva();
        ArrayList<Cargo> cargos = cjd.obtenerCargos();
        
        for(int i = 0 ; i < cargos.size() ; i++){
            switch(cargos.get(i).getNombre()){
                case "Presidente":
                    if(!(cargos.get(i).getIdSocio() == null)){
                        socio = obtenerSocio(cargos.get(i).getIdSocio());
                        jComboBox1.setSelectedItem(socio.toString());
                    }else{
                        jComboBox1.setSelectedItem("Ninguno");
                    }
                break;
                case "Vicepresidente":
                    if(!(cargos.get(i).getIdSocio() == null)){
                        socio = obtenerSocio(cargos.get(i).getIdSocio());
                        jComboBox2.setSelectedItem(socio.toString());
                    }else{
                        jComboBox2.setSelectedItem("Ninguno");
                    }
                break;
                case "Secretario":
                    if(!(cargos.get(i).getIdSocio() == null)){
                        socio = obtenerSocio(cargos.get(i).getIdSocio());
                        jComboBox3.setSelectedItem(socio.toString());
                    }else{
                        jComboBox3.setSelectedItem("Ninguno");
                    }
                break;
                case "Tesorero":
                    if(!(cargos.get(i).getIdSocio() == null)){
                        socio = obtenerSocio(cargos.get(i).getIdSocio());
                        jComboBox4.setSelectedItem(socio.toString());
                    }else{
                        jComboBox4.setSelectedItem("Ninguno");
                    }
                break;
                case "Vocal1":
                    if(!(cargos.get(i).getIdSocio() == null)){
                        socio = obtenerSocio(cargos.get(i).getIdSocio());
                        jComboBox5.setSelectedItem(socio.toString());
                    }else{
                        jComboBox5.setSelectedItem("Ninguno");
                    }
                break;
                case "Vocal2":
                    if(!(cargos.get(i).getIdSocio() == null)){
                        socio = obtenerSocio(cargos.get(i).getIdSocio());
                        jComboBox6.setSelectedItem(socio.toString());
                    }else{
                        jComboBox6.setSelectedItem("Ninguno");
                    }
                break;
            }
            
        }
    }
    
    //Obtiene un socio dado su dni
    private Socio obtenerSocio(String dni){
        ControlSocio cs = new ControlSocio();
        Socio socio = cs.obtenerSocio(dni);
        return socio;
    }       
    
    //Rellena el combo box con los nombres de todos los socios
    private void rellenarComboBox(){
        ControlSocio cs = new ControlSocio();
        ArrayList<Socio> soc = cs.obtenerSocios();
        jComboBox1.addItem("Ninguno");
        jComboBox2.addItem("Ninguno");
        jComboBox3.addItem("Ninguno");
        jComboBox4.addItem("Ninguno");
        jComboBox5.addItem("Ninguno");
        jComboBox6.addItem("Ninguno");
        for(int i = 0 ; i < soc.size() ; i++){
            jComboBox1.addItem(soc.get(i).toString());
            jComboBox2.addItem(soc.get(i).toString());
            jComboBox3.addItem(soc.get(i).toString());
            jComboBox4.addItem(soc.get(i).toString());
            jComboBox5.addItem(soc.get(i).toString());
            jComboBox6.addItem(soc.get(i).toString());
        }        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
